logging:
  level:
    org.apache.zookeeper.ClientCnxn: WARN


management:
  security:
    enabled: false
      
spring:
  application:
    name: UserRolesConsumer
  cloud:
    zookeeper:
      discovery:
        enabled: true

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

UserRolesConsumer:
  ribbon:
    listOfServers: localhost:9080