INSERT INTO USER(userid,USERNAME,PASSWORD) VALUES('1','username','$2a$10$Wtd4.V91xDc6xWUmHlPZrOZnp3lp9uDuhAhwyUUjtIdSaNqvT7Qya');
INSERT INTO USER(userid,USERNAME,PASSWORD) VALUES('3','riddhik','$2a$10$Wtd4.V91xDc6xWUmHlPZrOZnp3lp9uDuhAhwyUUjtIdSaNqvT7Qya');
INSERT INTO USER(userid,USERNAME,PASSWORD) VALUES('4','nameofme','$2a$10$Wtd4.V91xDc6xWUmHlPZrOZnp3lp9uDuhAhwyUUjtIdSaNqvT7Qya');
INSERT INTO USER(userid,USERNAME,PASSWORD) VALUES('5','newuser','$2a$10$Wtd4.V91xDc6xWUmHlPZrOZnp3lp9uDuhAhwyUUjtIdSaNqvT7Qya');
INSERT INTO roles(roleid,ROLE_NAME  ) VALUES('1', 'ADMIN');
INSERT INTO roles(roleid,ROLE_NAME  ) VALUES('2', 'FINANCE');

INSERT INTO users_roles VALUES(1,2);
INSERT INTO users_roles VALUES(1,1);

INSERT INTO ROLESPERMISSION VALUES ('1','VIEW',1);
INSERT INTO ROLESPERMISSION VALUES ('2','EDIT',1);
INSERT INTO ROLESPERMISSION VALUES ('3','VIEW',2);