INSERT INTO USER(userid,USERNAME,PASSWORD) VALUES('1','username','$2a$10$Wtd4.V91xDc6xWUmHlPZrOZnp3lp9uDuhAhwyUUjtIdSaNqvT7Qya');
INSERT INTO USER(userid,USERNAME,PASSWORD) VALUES('3','riddhik','$2a$10$Wtd4.V91xDc6xWUmHlPZrOZnp3lp9uDuhAhwyUUjtIdSaNqvT7Qya');
INSERT INTO USER(userid,USERNAME,PASSWORD) VALUES('4','nameofme','$2a$10$Wtd4.V91xDc6xWUmHlPZrOZnp3lp9uDuhAhwyUUjtIdSaNqvT7Qya');
INSERT INTO USER(userid,USERNAME,PASSWORD) VALUES('5','newuser','$2a$10$Wtd4.V91xDc6xWUmHlPZrOZnp3lp9uDuhAhwyUUjtIdSaNqvT7Qya');
INSERT INTO roles(roleid,ROLE_NAME,USERROLEPERMISSION  ) VALUES('1', 'ADMIN', 'VIEW,EDIT');
INSERT INTO roles(roleid,ROLE_NAME,USERROLEPERMISSION  ) VALUES('2', 'FINANCE', 'VIEW');
INSERT INTO users_roles VALUES(1,2);
INSERT INTO users_roles VALUES(1,1);

